### ISSUE TITLE
no method 'filter'

### ISSUE THREAD

**Issue by vinnitu** [dmapper/share-access#7]
```
> coffee server.coffee

Master pid  14891
TypeError: Object #<Backend> has no method 'filter'
  at Function.exports.setup (/home/user/project/node_modules/share-access/lib/index.js:28:15)
  at Racer.<anonymous> (/home/user/project/node_modules/share-access/lib/index.js:18:13)
  at Racer.emit (events.js:95:17)
  at Racer.createStore (/home/user/project/node_modules/derby/node_modules/racer/lib/Racer.server.js:9:8)
  at module.exports (/home/user/project/server/store.coffee:13:17)
  at /home/user/project/server.coffee:29:11
  at Racer.Derby.run (/home/user/project/node_modules/derby/lib/Derby.server.js:17:5)
  at Object.<anonymous> (/home/user/project/server.coffee:20:7)
  at Object.<anonymous> (/home/user/project/server.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.exports.run (/home/user/project/node_modules/coffee-script/lib/coffee-script/coffee-script.js:134:23)
  at compileScript (/home/user/project/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/home/user/project/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/home/user/project/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/home/user/project/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:935:3
```

I have derby 0.7.1 and only 2 additionsl code lines in server.coffee

```
async = require 'async'
derby = require 'derby'

shareAccess = require 'share-access'
derby.use shareAccess
```

**Comment by vinnitu** [comment]
I move to otherplace in server.coffee

```
  ...
  server.on 'upgrade', upgrade

  derby.use shareAccess
  shareAccess.allowCreate 'items', (docId, doc, session) ->
    console.log "allowCreate", {docId, doc, session}
    true
```

and error gone, but shareAccess.allowCreate() callback is never called

**Comment by minicuper** [comment]
use sharedb-access with derby 0.6.0 and greater
